### ISSUE TITLE
Admins

### ISSUE THREAD

**Issue by rmetzger** [ververica/flink-ecosystem#19]
list of github usernames that can always edit or delete

**Comment by sorahn** [comment]
Who are the admins? 

And the github username is mutable, so we should use the IDs.

**Comment by rmetzger** [comment]
StephanEwen,tillrohrmann,hsaputra,gyfora,uce,fhueske,zentol,aljoscha,rmetzger,twalthr,mbalassi,tzulitai,greghogan,warneke,vasia,alanfgates,mxm,shaoxuan-wang,sunjincheng121

I didn't know they are mutable :( 
Can you find out the IDs ?

**Comment by sorahn** [comment]
It appears that I can...

`curl -s https://github.com/<user> | awk -F '\/|[?]s=' '/og:image/ {print $5}'`
