### ISSUE TITLE
Do we need to let the `edit` and `remove` a first-class button

### ISSUE THREAD

**Issue by klion26** [ververica/flink-ecosystem#59]
![image](https://user-images.githubusercontent.com/1425623/61424792-3e081500-a947-11e9-98f1-b964ec14069d.png)

Do we need to let the `edit` and `remove` a first-class button on the page, currently, we need to click twice when wants to edit some package

**Comment by rmetzger** [comment]
I'm not sure if this is really a necessary change. These actions are done fairly rarely, only by the owners of the package.

**Comment by rmetzger** [comment]
I would suggest to leave this ticket open to see if others have the same concern, but I would not suggest to start working on it.
